FROM hub.yottab.io/library/node:18-alpine as base
WORKDIR /app

COPY vite.config.js ./
COPY package.json ./
COPY .eslintrc.cjs ./
COPY tailwind.config.js ./
COPY postcss.config.js ./
RUN npm i 

COPY public ./public
COPY src ./src
COPY index.html ./

RUN BUILD_PATH=build

RUN npm run build
FROM hub.yottab.io/library/nginx/nginx-spa:stable as final

WORKDIR /app
COPY --from=base /app/dev-build /app
CMD ["nginx"]