FROM hub.yottab.io/library/node:18-alpine as base
WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .


RUN npm run build
FROM hub.yottab.io/library/nginx/nginx-spa:stable as final

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80/tcp

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]